version: 0.2

phases:
  install:
    commands:
      - echo installing nodejs
      - sudo apt-get update
      - curl -s https://deb.nodesource.com/setup_16.x | sudo bash
      - sudo apt install nodejs -y
      - node -v
      - echo installing serverless
      - npm install -g serverless

  pre_build:
    commands:
      - echo nothing to do on prebuild
      - export AWS_ACCESS_KEY_ID=$KEY
      - export AWS_SECRET_ACCESS_KEY=$SECRET
      - export AWS_DEFAULT_REGION=ap-south-1

  build:
    commands:
      - echo deployment started on `date`
      - serverless deploy

  post_build:
    commands:
      - echo deployment completed on `date`
