service: sls-lambda
frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x
  profile: abehera-dev
  region: ap-south-1
  stage: ${opt:stage, 'dev'}

functions:
  function1:
    handler: index.handler
